---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: otp-street-builder-hsl-v3
spec:
  schedule: "30 1 * * *" # schedule in Finland time
  timeZone: "Europe/Helsinki"
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 4
  jobTemplate:
    spec:
      backoffLimit: 2 # max two retries
      template:
        metadata:
          labels:
            app: otp-street-builder-hsl-v3
        spec:
          activeDeadlineSeconds: 9000 # one build can take max 2 hours and 30 minutes
          restartPolicy: OnFailure
          nodeSelector:
            agentpool: builderpool
          tolerations:
          - key: "builder"
            operator: "Equal"
            value: "yes"
            effect: "NoSchedule"
          containers:
          - name: otp-street-builder-hsl-v3
            image: hsldevcom/otp-data-builder:v3
            volumeMounts:
            - mountPath: /opt/otp-data-builder/storage
              name: datastorage
            imagePullPolicy: Always
            securityContext:
              privileged: true
              capabilities:
                add:
                 - NET_ADMIN
                 - SYS_ADMIN
            env:
            - name: ROUTER_NAME
              value: "hsl"
            - name: BUILDER_TYPE
              value: "HSL dev v3"
            - name: EXTRA_SRC
              value: "{\"KirkkonummiE\": {\"url\": \"https://gtfsdata.blob.core.windows.net/hsl/hsl_flex_test1-gtfs.zip\"},\"KirkkonummiP\": {\"url\": \"https://gtfsdata.blob.core.windows.net/hsl/hsl_flex_test2-gtfs.zip\"}, \"HSL\": {\"url\": \"https://geocoding.blob.core.windows.net/vrk/HSL-gtfs.zip\"}}"
            - name: EXTRA_UPDATERS
              value: "{\"liipi\": {\"facilitiesUrl\": \"https://parking-test.fintraffic.fi/api/v1/facilities.json?limit=-1\", \"utilizationsUrl\": \"https://parking-test.fintraffic.fi/api/v1/utilizations.json?limit=-1\", \"hubsUrl\": \"https://parking-test.fintraffic.fi/api/v1/hubs.json?limit=-1\"}}"
            - name: DOCKER_TAG
              value: "v3"
            - name: SLACK_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-access-token
                  key: slack-access-token
            - name: SLACK_CHANNEL_ID
              valueFrom:
                secretKeyRef:
                  name: slack-ci-channel-id
                  key: slack-ci-channel-id
            - name: OTP_TAG
              value: "v2"
            - name: SEED_TAG
              value: "v3"
            - name: TOOLS_TAG
              value: "v3"
            - name: JAVA_OPTS
              value: "-Xmx24G -Xms24G"
            - name: SPLIT_BUILD_TYPE
              value: "ONLY_BUILD_STREET_GRAPH"
            resources:
              requests:
                memory: 26Gi
                cpu: 7000m
              limits:
                memory: 26Gi
                cpu: 8000m
          imagePullSecrets:
            - name: hsldevcomkey
          volumes:
            - name: "datastorage"
              nfs:
                server: digitransitdevaksstrg.file.core.windows.net
                path: /digitransitdevaksstrg/hsl
                readOnly: false

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: otp-street-builder-hsl-v3-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: otp-street-builder-hsl-v3
